// <auto-generated />
namespace DBMigrator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-alpha3-20222")]
    public sealed partial class ForumTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForumTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201304202057579_ForumTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
