// <auto-generated />
namespace Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SecondVideoType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondVideoType));
        
        string IMigrationMetadata.Id
        {
            get { return "201301062146180_SecondVideoType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
