// <auto-generated />
namespace Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Log4NetTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Log4NetTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201302100728285_Log4NetTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
