// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DasKlub.DBMigrator.Migrations
{
    public sealed partial class GetAllRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetAllRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201212030042299_GetAllRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
