// <auto-generated />
namespace DBMigrator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class EF6BetaUpgrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EF6BetaUpgrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201308210410244_EF6BetaUpgrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
