// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DasKlub.DBMigrator.Migrations
{
    public sealed partial class FindUserFilter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FindUserFilter));
        
        string IMigrationMetadata.Id
        {
            get { return "201303242032014_FindUserFilter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
