// <auto-generated />
namespace Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ContestResults : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContestResults));
        
        string IMigrationMetadata.Id
        {
            get { return "201301190831387_ContestResults"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
